[project]
name = "nn"
version = "0.1.0"
description = "Dead-simple NN 'library' for educational purposes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
]
